module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-background": "var(--app-background)",
        baseblack: "var(--baseblack)",
        basewhite: "var(--basewhite)",
        "brand-600": "var(--brand-600)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-900": "var(--gray-900)",
        "label-colorlightprimary": "var(--label-colorlightprimary)",
        "neutralash-03": "var(--neutralash-03)",
        "neutralash-04": "var(--neutralash-04)",
        "neutralash-05": "var(--neutralash-05)",
        "primarypetrol-blue-01": "var(--primarypetrol-blue-01)",
        "primarypetrol-blue-02": "var(--primarypetrol-blue-02)",
        "primarypetrol-blue-03": "var(--primarypetrol-blue-03)",
        "primarypetrol-blue-05": "var(--primarypetrol-blue-05)",
        "secondaryfuchsia-pink-02": "var(--secondaryfuchsia-pink-02)",
        "separator-colorlightwith-transparency":
          "var(--separator-colorlightwith-transparency)",
        "system-backgroundlightprimary": "var(--system-backgroundlightprimary)",
        "tertiarygraph-green-04": "var(--tertiarygraph-green-04)",
        "warning-100": "var(--warning-100)",
        "warning-50": "var(--warning-50)",
        "warning-600": "var(--warning-600)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "action-button-01": "var(--action-button-01-font-family)",
        "action-button-02": "var(--action-button-02-font-family)",
        "body-regular": "var(--body-regular-font-family)",
        "headings-heading-02": "var(--headings-heading-02-font-family)",
        "headings-heading-03": "var(--headings-heading-03-font-family)",
        "headings-heading-04": "var(--headings-heading-04-font-family)",
        "headings-heading-06": "var(--headings-heading-06-font-family)",
        "headings-heading-07": "var(--headings-heading-07-font-family)",
        "text-body-01": "var(--text-body-01-font-family)",
        "text-body-02": "var(--text-body-02-font-family)",
        "text-caption-01": "var(--text-caption-01-font-family)",
        "text-caption-02": "var(--text-caption-02-font-family)",
        "text-footnote-01": "var(--text-footnote-01-font-family)",
        "text-footnote-02": "var(--text-footnote-02-font-family)",
        "text-LABEL-02": "var(--text-LABEL-02-font-family)",
        "text-LABEL-03": "var(--text-LABEL-03-font-family)",
        "text-lg-semibold": "var(--text-lg-semibold-font-family)",
        "text-md-semibold": "var(--text-md-semibold-font-family)",
        "text-sm-regular": "var(--text-sm-regular-font-family)",
        "text-xs-semibold": "var(--text-xs-semibold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "backdrop-blurs-backdrop-blur-md":
          "var(--backdrop-blurs-backdrop-blur-md)",
        "focus-rings-ring-brand-shadow-xs":
          "var(--focus-rings-ring-brand-shadow-xs)",
        "shadows-shadow-xl": "var(--shadows-shadow-xl)",
        "shadows-shadow-xs": "var(--shadows-shadow-xs)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
