// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-album-title/TitleOverview.tsx": () => import("../components/mockups/admin-album-title/TitleOverview.tsx"),
  "./components/mockups/admin-videos-box/DropzoneFirst.tsx": () => import("../components/mockups/admin-videos-box/DropzoneFirst.tsx"),
  "./components/mockups/admin-videos-box/EditorModal.tsx": () => import("../components/mockups/admin-videos-box/EditorModal.tsx"),
  "./components/mockups/admin-videos-box/GalleryEmpty.tsx": () => import("../components/mockups/admin-videos-box/GalleryEmpty.tsx"),
  "./components/mockups/admin-videos-box/GalleryGrid.tsx": () => import("../components/mockups/admin-videos-box/GalleryGrid.tsx"),
  "./components/mockups/admin-videos-box/GallerySheet.tsx": () => import("../components/mockups/admin-videos-box/GallerySheet.tsx"),
  "./components/mockups/admin-credits-row/Progressive.tsx": () => import("../components/mockups/admin-credits-row/Progressive.tsx"),
  "./components/mockups/admin-credits-row/ProgressiveV2.tsx": () => import("../components/mockups/admin-credits-row/ProgressiveV2.tsx"),
  "./components/mockups/admin-credits-row/ProgressiveV3.tsx": () => import("../components/mockups/admin-credits-row/ProgressiveV3.tsx"),
  "./components/mockups/admin-credits-row/Stacked.tsx": () => import("../components/mockups/admin-credits-row/Stacked.tsx"),
  "./components/mockups/admin-credits-row/TwoColumn.tsx": () => import("../components/mockups/admin-credits-row/TwoColumn.tsx")
};
